name: Agentboard
options:
  bundleIdPrefix: com.arthurteller
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  SwiftTerm:
    url: https://github.com/migueldeicaza/SwiftTerm
    majorVersion: 1.0.0

targets:
  Agentboard:
    type: application
    platform: iOS
    sources:
      - Agentboard
    settings:
      base:
        INFOPLIST_FILE: Agentboard/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.arthurteller.Agentboard
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: N5KJ74ZM82
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - package: SwiftTerm
    info:
      path: Agentboard/Info.plist
      properties:
        CFBundleName: Agentboard
        CFBundleDisplayName: Agentboard
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: $(PRODUCT_TYPE)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - armv7
        LSRequiresIPhoneOS: true
        UIAppFonts:
          - JetBrainsMono-Regular.ttf
          - JetBrainsMono-Bold.ttf
          - DMMono-Regular.ttf
          - DMMono-Medium.ttf
          - SpaceMono-Regular.ttf
          - SpaceMono-Bold.ttf
        NSLocalNetworkUsageDescription: "Agentboard needs local network access to discover and connect to Claude Code servers on your network."
        NSBonjourServices:
          - _agentboard._tcp
